//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IISAutoParts.DBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class provide
    {
        public int id { get; set; }
        public Nullable<int> provideNumber { get; set; }
        public Nullable<int> idList { get; set; }
        public Nullable<System.DateTime> dateDelivery { get; set; }
        public Nullable<int> idProvider { get; set; }
    }
}
