//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IISAutoParts.DBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public Nullable<int> role { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> dateEnter { get; set; }
        public string permission { get; set; }
        public string name { get; set; }
    }
}
